name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: DesignSecureArchitecture/NAT-Gateway
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_WORKING_DIR: ${{ github.workspace }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Show Present Working Directory
        run: |
          echo "Present Working Directory:"
          TF_WORKING_DIR = pwd
          echo "Terraform Working Directory:"
          echo "$TF_WORKING_DIR"

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init and Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init
          terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

