name: Terraform Deployment
on:
  push:
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets['AWS_SECRET_ACCESS_KEY'] }}"

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform Init
        run: terraform init
        working-directory: ./DesignSecureArchitecture/IAM-users-groups-creation
      - name: Terraform plan
        run: terraform plan
        working-directory: ./DesignSecureArchitecture/IAM-users-groups-creation
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./DesignSecureArchitecture/IAM-users-groups-creation


