name: Terraform Deployment
on:push
    jobs: 
        deploy: 
            runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Set Up Terraform 
              uses: hashicorp/setup-terraform@v3
              with: 
                terraform_version: 1.12.2
                
